### ISSUE TITLE
Some problem with the multi_stage_parser, cannot run evaluation

### ISSUE THREAD

**Issue by ShaRefOh** [csensemakers/desci-sense#102]
It was probably a committed change that had happened lately... Really need to add the tests.

(base) shaharorielkagan@shahars-MacBook-Air-2 desci-sense % python3 desci_sense/evaluation/eval_benchmark_v0.py --dataset='common-sense-makers/evaluation_benchmark/dataset_for_eval:v0'
Traceback (most recent call last):
  File "/Users/shaharorielkagan/Documents/Python/desci-sense/desci_sense/evaluation/eval_benchmark_v0.py", line 32, in <module>
    from desci_sense.runner import init_model, load_config
  File "/Users/shaharorielkagan/Documents/Python/desci-sense/desci_sense/runner.py", line 6, in <module>
    from desci_sense.parsers.multi_stage_parser import MultiStageParser
  File "/Users/shaharorielkagan/Documents/Python/desci-sense/desci_sense/parsers/multi_stage_parser.py", line 10, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

@ronentk is there a quick fix?

**Comment by ronentk** [comment]
Hey, try 
`pip install loguru`

**Comment by ShaRefOh** [comment]
Haha, Yep, it worked; seems I need to add some notion db id. do you know what it is?

**Comment by ShaRefOh** [comment]
installed and added needed keys
